#!/bin/sh

PATH_TO_SCRIPT=$(cd ${0%/*} && echo $PWD/${0##*/})
PROGRAMPREFIX=`dirname "$PATH_TO_SCRIPT"`

$PROGRAMPREFIX/build/src/WP4.wt --docroot $PROGRAMPREFIX/ --approot $PROGRAMPREFIX/ --http-port 8080 --http-addr 0::0  $@
